# Generated by Django 5.0.2 on 2024-03-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = []
