# Generated by Django 5.0.2 on 2024-03-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20240303_2027"),
    ]

    operations = []
