# Generated by Django 5.0.2 on 2024-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20240303_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
